### ISSUE TITLE
NAS-9 Evaluation Einlesen in DB & Restarbeiten

### ISSUE THREAD

**Issue by chseip** [pkorduan/xmi2db#31]
## TODOs:
- [x] um's "&"-Zeichen kümmern, erledigt in NAS-9-1, übernommen in develop
- [x] um Sonderzeichen (ß etc.) kümmern, erledigt in NAS-9-1, übernommen in develop
- [x] statt 'false' => '0' sein und statt 'true' => '1' in den XML's , erledigt in NAS-9-1, übernommen in develop
- [x] wkb_geometry statt position, erledigt in dev-7
- [x] ogc_fid und identifier Spalten hinzufügen, erledigt in NAS-9-1
- [x] warum so viel mehr Tupel in Original Schema?
Kann man nicht vergleichen, weil es mehr Tabellen sind im neuen Schema und damit auch mehr Tupel. Man könnte höchstens einzelne Tabellen vergleichen. Aber warum sollten hier unterschiedlich viele drin sein?
## Grundlegendes

**Einlesen der Original ALKIS datei ins Original-Schema (http://www.kvwmap.de/alkis/alkis_schema.sql, 'alkis')**
`ogr2ogr -f "PostgreSQL" --config PG_USE_COPY YES -skipfailures -nlt CONVERT_TO_LINEAR -append PG:"dbname=nastest active_schema=alkis user=kvwmap password=XxX host=pgsql port=5432" -a_srs EPSG:25833  /var/www/data/alkis/postnas/AX_Bestandsdatenauszug_nas.xml 2>> postnas_err.log`

**Einlesen des verflachten (renamed) Datei ins neue Schema ('aaa_ogr')**
`ogr2ogr -f "PostgreSQL" --config PG_USE_COPY YES -skipfailures -nlt CONVERT_TO_LINEAR -append PG:"dbname=nastest active_schema=aaa_ogr user=kvwmap password=XxX host=pgsql port=5432" -a_srs EPSG:25833  /var/www/data/alkis/postnas/AX_Bestandsdatenauszug_nas_renamed.xml 2>> postnas_renamed_err.log`

**Zum Fehler ausbügeln, vorher Leeren aller Tabellen:**
1. Funktion `truncate_schema()` anlegen (http://stackoverflow.com/a/27794841/6532988)
2. `SELECT truncate_schema('aaa_ogr')`
### Geschwindigkeit (Bash `time`)

Original ALKIS: 23m42s
Verflachtes ALKIS: 2m21s
### Vergleich Tabelle 'ax_flurstueck'

**Zeilen**
original: 1078 Zeilen
renamed: 1078 Zeilen

**Attribute**
- fehlen in original ggü. renamed (wichtige):
  - art character varying[], -- zeigtAufExternes AA_Fachdatenverbindung|art  URI 1
  - name text[], -- zeigtAufExternes AA_Fachdatenverbindung|fachdatenobjekt|AA_Fachdatenobjekt|name   1
  - uri character varying[], -- zeigtAufExternes AA_Fachdatenverbindung|fachdatenobjekt|AA_Fachdatenobjekt|uri  URI 1
  - angabenzumabschnittstelle text[], -- sonstigeEigenschaften AX_SonstigeEigenschaften_Flurstueck|angabenZumAbschnittStelle   0..1
- fehlen in renamed ggü. original:
  - ogc_fid serial NOT NULL
### Vergleich aller Tabellen

über:

```
SELECT schemaname,relname,n_live_tup 
  FROM pg_stat_user_tables
  WHERE n_live_tup > 0
  ORDER BY relname ASC;
```

bzw.

```
SELECT schemaname,SUM(n_live_tup)
  FROM pg_stat_user_tables
  GROUP BY schemaname;
```

**Original Schema**
- Anzahl Tabellen mit inhalt: 141
- Anzahl Tupel: 78.471

**Verflachtes Schema**
- Anzahl Tabellen mit inhalt: 283
- Anzahl Tupel: 11.319

**Details**
- `alkis_beziehungen`
  - Original: 27.462
  - Verflacht: 4.560
- `ap_pto`
  - Original: 1.796
  - Verflacht: 1.078
- `ax_besonderertopographischerpunkt`
  - Original: 5.538
  - Verflacht: 0
- `ax_artderfestlegung_denkmalschutzrecht`
  - Original: 0
  - Verflacht: 72
- Anderer Tabname:
  - Original: `ax_buchungsstelle_buchungsart`
  - Verflacht: `ax_buchungsart_buchungsstelle`
### Probleme/Fehler beim Einlesen
- Fehler "ERROR 1: XML Parsing Error: expected entity name for reference at line 327290, column 82"
  - zugehörige Zeile: "<beschriebDerRechtsgemeinschaft>Heinz Liebherr Verwaltungsgesellschaft mbH & Co. K</beschriebDerRechtsgemeinschaft>"
    => Problem beim Parsen des "&"-Zeichens?
- Fehler "Warning 1: Value 'false' of field ax_flurstueck.abweichenderrechtszustand parsed incompletely to integer 0."
  - statt 'false' müsste es '0' sein und statt 'true' dann '1' (siehe /var/www/data/alkis/postnas/AX_Bestandsdatenauszug_nas_renamed_cs.xml)

**Inhalte**
Zelle in 'angabenzumabschnittflurstueck' in original: '{"Riß 67"}'
Zelle in 'angabenzumabschnittflurstueck' in renamed: '{"Ri?? 67"}'
Hat sich erledigt durch encoding des Textes in NAS-9-1 behoben.
### OGR verlangt die Geometrie als wkb_geometry von markus-hentschel

Im ogr Schema werden die Spalten position jetzt alle in wkb_geometry angelegt.

**Comment by markus-hentschel** [comment]
OGR verlangt die Geometrie als "wkb_geometry".

**Comment by weideman** [comment]
Warum wird _PG_USE_COPY NO_ anstelle von _PG_USE_COPY YES_ in der Datei _import_nas.sh_
verwendet?

Wir hatte bei ogr2ogr mit PG_USE_COPY YES mal Fehlermeldungen und haben deswegen auf NO umgestellt. Ich weiß jetzt nicht mehr welche Version das betraf, aber es sollte prinzipiell auch mit YES gehen und dann auch schneller sein. Ich werde auch noch mal mit YES testen und dann den Fehler reporten falls er wieder auftritt.

**Comment by markus-hentschel** [comment]
Bei uns ist PG_USE_COPY in der Produktionsumgebung ebenfalls YES, einen Grund kann ich allerdings so aus dem Hut nicht angeben.

**Comment by markus-hentschel** [comment]
**Fehlermeldungen rename_nas.rb**
In der Doku fehlt der Hinweis, dass in der rename_nas.rb die Variable renamefile richtig gesetzt sein muss.
Wenn man rename_nas.rb startet, kommen zwei Meldungen und das script bricht ab:
- Der Umlaut in Zeile 8 wird angemeckert
- In Zeile 27 (von rename_nas.rb?):  in `<main>': uninitialized constant LibXML::XML::Writer (NameError)

[rename_nas.rb:8](https://github.com/pkorduan/xmi2db/blob/develop/converter/rename_nas.rb#L8)  enthält einen Umlaut. Das ist aber nur Ausgabetext. Hast Du die Datei in UTF-8 gespeichert?
[rename_nas.rb:27](https://github.com/pkorduan/xmi2db/blob/develop/converter/rename_nas.rb#L27)  initialisiert und das Writer Objekt und öffnet die Datei outfile. Ich vermute mal, dass die Datei auf Deinem System nicht angelegt werden kann, z.B. wegen Schreibrechten. Du kannst die Ausgabedatei entweder als 2. Parameter angeben oder es wird der Name der Eingabedatei genommen mit Zusatz _renamed im Dateinamen. Du kannst ihn Dir auch mal ausgeben lassen wenn Du vor die besagte Zeile 8 w = XML::Writer.file outfile folgendes eingibst:
<code>puts "Ausgabedatei: " + outfile</code>
Das zeigt Dir die Datei an, die angelegt werden soll. Im Verzeichnis muss der Nutzer, der das Skript ausführt Schreibrechte haben.
Der Hinweis auf die Angabe von renamefile wurde in der [README.md:76] gesetzt. Ich habe den Pfad im Commit [https://github.com/pkorduan/xmi2db/commit/2c4b7fee253227c677d02cff93d24f5468977261] auch noch mal so angepasst, dass er relativ zum Skript steht. [rename_nas.rb:1](https://github.com/pkorduan/xmi2db/blob/develop/converter/rename_nas.rb#L1) Dadurch muss man den Pfad eigentlich nicht  mehr anpassen, es sei denn der Dateiname oder Ort des Skriptes wird geändert. Aber warum sollte man das tun?
Lösung:
Nach genauerem Testen ist aufgefallen, dass auf diesem Rechner eine veraltete Version von libxml_ruby verwendet wurde. libxml_ruby sollte aktuell sein, also derzeit mindestens Version 2.9. Die ältere kannte noch gar nicht die Klasse Writer.

**Comment by jef-n** [comment]
Gibt es einen Grund warum keine direkten Links auf das Code-Repository in den Issues auftauchen (z.B. [rename_nas.rb:8](https://github.com/pkorduan/xmi2db/blob/e908b1f1e268fdb512126ef729b41affa3dbdce0/converter/rename_nas.rb#L8) und [rename_nas.rb:27](https://github.com/pkorduan/xmi2db/blob/e908b1f1e268fdb512126ef729b41affa3dbdce0/converter/rename_nas.rb#L27))?

Auch kann man Bezüge auf Commits verwenden oder die Issue-Nummer bereits in der Commit-Message erwähnen, um einen automatischen Link im Issue zu erhalten (wenn "#31" statt oder zusätzlich zu NAS-9-1 in der Commit-Message zu 58933f1c gestanden hätte, wäre hier schon ein Link aufgetaucht).

Dann könnte man dem ganzen IMHO viel leichter folgen...

**Comment by markus-hentschel** [comment]
Der Grund lautet: Newbie. Ich weiß gerade mal, dass ich einen comment hinterlassen kann...

**Comment by jef-n** [comment]
@markus-hentschel ich meinte auch eher @pkorduan und @chseip.  Bei kaum einem der Tickets sind mir Querverweise aufgefallen.  Zuerst dachte ich auf github wären nur die Tickets und der Code wäre woanders...

**Comment by pkorduan** [comment]
Die Typen von einigen Aufzählungen wurde nicht richtig angewendet. ax_punktortau.genauigkeitsstufe und vertrauenswuerdigkeit sollen integer sein, nicht character varying. Das wurde in dem Commit 8db52475 behoben.

**Comment by pkorduan** [comment]
Im Script rename_nas.rb gab es noch einen Fehler beim Erkennen von leeren Tags. Tags in der Form <tag></tag> wurden zwei mal geschlossen. Damit wurde der Tag des Elternelementes zu früh geschlossen und im Testfall von Herrn Schmidt das Ganze Dokument zu früh geschlossen. Der Fehler wurde im Commit 27114e53 behoben.

**Comment by pkorduan** [comment]
Der vollständige Filter für mv wurde hinzugefügt im Commit ec052664.
